name: Test build and package QubesOS RPMs

on:
  workflow_call:
    inputs:
      qubes-component:
        description: >
          Name of QubesOS component as recognized by its build system.
        required: true
        type: string
      qubes-pkg-src-dir:
        description: >
          Relative path to directory containing Qubes OS package.
        required: false
        type: string
      qubes-pkg-revision:
        description: >
          Forced revision of a package.
        required: false
        type: string
      qubes-pkg-version:
        description: >
          Forced version of a package.
        required: false
        type: string

jobs:
  build-and-package:
    runs-on: ubuntu-24.04
    name: Compile and package RPM
    permissions:
      # for publishing releases
      contents: write

    steps:
      - name: Prepare SSH key
        shell: bash
        run: |
          mkdir -p ~/.ssh
          echo "${{secrets.GITEA_DEPLOY_KEY}}" > ~/.ssh/gitea_deploy_key
          sed -i 's/\r//' ~/.ssh/gitea_deploy_key
          chmod 600 ~/.ssh/gitea_deploy_key
          echo -e "\n
          Host git.3mdeb.com\n
          HostName       git.3mdeb.com\n
          StrictHostKeyChecking no\n
          UserKnownHostsFile /dev/null\n
          IdentityFile   ~/.ssh/gitea_deploy_key\n
          IdentitiesOnly yes" > ~/.ssh/config_deploy

      - name: Install dependencies of builder script
        # docker.io was changed to docker because of conflict on containerd
        run: |
          sudo apt install --no-install-recommends --yes \
          createrepo-c devscripts gpg python3-docker reprepro \
          python3-pathspec mktorrent python3-lxml python3-dateutil \

      - name: Import the test CI signing private key
        run: |
          echo "${{ secrets.TEST_CI_PRIVATE_KEY }}" | gpg --batch --import

      - name: Compile sq
        run: |
          sudo apt install --no-install-recommends --yes \
          build-essential capnproto clang curl git libassuan-dev libbz2-dev \
          libgpgme-dev libnpth-dev libsqlite3-dev libssl-dev nettle-dev \
          pkg-config zlib1g-dev && \
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y && \
          source "$HOME/.cargo/env" && \
          cargo install --version 1.3.1 --locked sequoia-sq && \
          sudo mv "$HOME/.cargo/bin/sq" /usr/local/bin/

      - uses: actions/checkout@v4
        with:
          repository: QubesOS/qubes-builderv2
          ref: 5327e41b3d68befc61bee87fb1ac0033662d575f
          fetch-depth: 0

      - name: Cache Docker image and dom0 stuff
        uses: actions/cache@v4
        id: docker-cache
        with:
          path: |
            /tmp/qubes-builder-fedora.tar
          key: |
            ${{ hashFiles('tools/*', 'dockerfiles/fedora.Dockerfile') }}-docker-container

      - name: Load Docker image
        if: steps.docker-cache.outputs.cache-hit == 'true'
        run: |
          docker load --input /tmp/qubes-builder-fedora.tar

      - name: Build Docker image (optional)
        if: steps.docker-cache.outputs.cache-hit != 'true'
        run: |
          sed -i "s/RUN useradd -m user$/RUN useradd -m user -u $UID/" dockerfiles/fedora.Dockerfile
          tools/generate-container-image.sh docker

      - name: Export Docker image (optional)
        if: steps.docker-cache.outputs.cache-hit != 'true'
        run: |
          docker save --output /tmp/qubes-builder-fedora.tar \
                      qubes-builder-fedora:latest

      - name: Prepare configuration
        env:
          URL: ${{ github.repositoryUrl }}
          COMPONENT: ${{ inputs.qubes-component }}
          PKG_DIR: ${{ inputs.qubes-pkg-src-dir }}
          PKG_REV: ${{ inputs.qubes-pkg-revision }}
          PKG_VER: ${{ inputs.qubes-pkg-version }}
          # Following 2 variables are used in double expansion '${${{ github.ref_type }}}',
          # do not change these names even though they don't follow the convention.
          branch: ${{ github.head_ref }}
          tag: ${{ github.ref_name }}
        run: |
          cp example-configs/qubes-os-r4.2.yml builder.yml
          # Switch from Qubes to Docker executor
          sed -i "/^executor:$/,+4d; /^#executor:$/,+3s/#//" builder.yml

          branch_name=${${{ github.ref_type }}}
          if [ -z "$branch_name" ]; then
              # github.head_ref is set only for pull requests, this should
              # handle pushes
              branch_name=$(basename "$GITHUB_REF")
          fi

          if [ -n "$PKG_DIR" ]; then
              #
              # 1. Clone repository locally
              # 2. Add files required by qubes-builderv2
              # 3. Commit them
              # 4. Put local path as a repository URL to configuration file
              #

              # `plugins/fetch` is copied inside Docker container, place clone there
              rel_clone_dir=plugins/fetch/tmp_clone
              clone_dir=qubesbuilder/$rel_clone_dir
              git clone --depth 1 --branch "$branch_name" "${URL/git:/https:}" "$clone_dir"

              # qubes-builderv2 expects top directory of extracted sources to
              # follow "name-version" naming scheme and will fail if other
              # naming is used
              #
              # At the same time when generating a source archive, it uses
              # naming scheme from `Source0`, which inevitably leads to a
              # failure if it's not what qubes-builderv2 expects.
              sed '/^Source0:/s/\t.*/\t%{name}-%{version}.tar.gz/' \
                  "$clone_dir/$PKG_DIR/$COMPONENT.spec.in" \
                  > "$clone_dir/$COMPONENT.spec.in.tmp"
              # Temporary file handles case when qubes-pkg-src-dir is set to '.'
              mv "$clone_dir/$COMPONENT.spec.in.tmp" "$clone_dir/$COMPONENT.spec.in"

              if [ -z "$PKG_REV" ]; then
                  PKG_REV=1
              fi
              echo "$PKG_REV" > "$clone_dir/rel"

              if [ -z "$PKG_VER" ]; then
                  PKG_VER="0+$(git -C "$clone_dir" show-ref -s "$branch_name" | head -1)"
              fi
              echo "$PKG_VER" > "$clone_dir/version"

              cat > "$clone_dir/.qubesbuilder" <<EOF
              host:
                rpm:
                  build:
                  - $COMPONENT.spec
          EOF
              git config --global user.name user.name
              git config --global user.email user.email
              git -C "$clone_dir" add .
              git -C "$clone_dir" commit -m 'CI changes'
              if [ ${{ github.ref_type }} = tag ]; then
                # Without this original commit is going to be used
                git -C "$clone_dir" tag -f "$branch_name"
              fi

              # If it's an existing component without options in builder.yml,
              # just remove the line from the file
              sed -i "/^  - $COMPONENT$/d" builder.yml

              # If it's an existing component with options in builder.yml,
              # rename it to a dummy component. This avoids having a duplicated
              # name and at the same time doesn't require the removal of options
              sed -i "/^  - $COMPONENT:$/c\ \ - does_not_exist:" builder.yml

              # Add a new component to builder.yml
              sed -i "/^components:/a\  - $COMPONENT:" builder.yml
              sed -i "/^  - $COMPONENT:/a\      verification-mode: insecure-skip-checking" builder.yml
              sed -i "/^  - $COMPONENT:/a\      branch: $branch_name" builder.yml
              sed -i "/^  - $COMPONENT:/a\      url: /builder/$rel_clone_dir" builder.yml

              echo "::group::version"
              cat $clone_dir/version
              echo "::endgroup::"

              echo "::group::$COMPONENT.spec.in"
              cat $clone_dir/$COMPONENT.spec.in
              echo "::endgroup::"

              echo "::group::.qubesbuilder"
              cat $clone_dir/.qubesbuilder
              echo "::endgroup::"
          else
              # It's an existing component that needs some overrides
              # "2C551A2BE60D4F0A317DCEBD68087B8608881D06" is a test CI key
              sed -i '1i sign-key:\n  rpm: "2C551A2BE60D4F0A317DCEBD68087B8608881D06"' builder.yml
              sed -i "1,/^  - $COMPONENT/s#^  - $COMPONENT#&:#" builder.yml
              sed -i "/^  - $COMPONENT:/a\      verification-mode: insecure-skip-checking" builder.yml
              sed -i "/^  - $COMPONENT:/a\      branch: $branch_name" builder.yml
              sed -i "/^  - $COMPONENT:/a\      url: ${URL/git:/https:}" builder.yml
          fi

          echo "::group::builder.yml"
          cat builder.yml
          echo "::endgroup::"

      - name: Disable AppArmor
        # Ubuntu runner with Fedora 42 Docker container fails due to AppArmor:
        # https://github.com/fedora-cloud/docker-brew-fedora/issues/117
        uses: cisagov/action-disable-apparmor@v1

      - name: Disable kernel.apparmor_restrict_unprivileged_userns
        # See the AppArmor failures above
        run: sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0

      - name: Build and package
        env:
          DEBUG: ${{ runner.debug == 1 && '--debug --verbose' || '' }}
        run: |
          ./qb $DEBUG -c ${{ inputs.qubes-component }} package fetch prep build sign
          rpms=( $(find "artifacts/components/${{ inputs.qubes-component }}/" -regex ".*/build/rpm/[^/]*.rpm") )
          cp --verbose "${rpms[@]}" .

      - name: Save built packages
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: qubesos.dom0.fc37-${{ inputs.qubes-component }}-${{ github.sha }}
          path: '*.rpm'

      - name: Construct release's description
        if: github.event_name == 'push' && github.ref_type == 'tag'
        run: |
          for artifact in *.rpm; do
            echo "### $artifact" >> release-body.md
            echo '```' >> release-body.md
            echo "wget --quiet '${{ github.server_url }}/${{ github.repository }}/releases/download/${{ github.ref_name }}/$artifact'" >> release-body.md
            echo '```' >> release-body.md
            echo '```' >> release-body.md
            echo "curl --remote-name '${{ github.server_url }}/${{ github.repository }}/releases/download/${{ github.ref_name }}/$artifact'" >> release-body.md
            echo '```' >> release-body.md
          done

      - name: Create release for a new tag
        if: github.event_name == 'push' && github.ref_type == 'tag'
        uses: ncipollo/release-action@v1.14.0
        with:
          artifacts: '*.rpm'
          artifactErrorsFailBuild: true
          bodyFile: "release-body.md"

      - name: Run Gitea workflow
        shell: bash
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          GIT_SSH_COMMAND='ssh -F ~/.ssh/config_deploy' git clone ssh://git@git.3mdeb.com:2222/zarhus/trenchboot-release-cicd-pipeline.git
          cd trenchboot-release-cicd-pipeline
          cp ../release-body.md .
          git add release-body.md
          git commit -m "Signing release ${{ github.ref_name }}"
          GIT_SSH_COMMAND='ssh -F ~/.ssh/config_deploy' git push origin devel
          git tag "${{ github.ref_name }}"
          GIT_SSH_COMMAND='ssh -F ~/.ssh/config_deploy' git push origin "${{ github.ref_name }}"
          cd -

  cleanup:
    name: Cleanup
    runs-on: ubuntu-24.04
    needs: build-and-package
    if: always()
    steps:
      - name: Cleanup after deployment
        shell: bash
        run: |
          rm -f ~/.ssh/gitea_deploy_key
          rm -rf trenchboot-release-cicd-pipeline
